apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-ingress
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  project: default
  source:
    repoURL: git@github.com:defi-magi/quest-eks-cluster-state.git
    path: apps/argo-ingress
    targetRevision: HEAD
    helm:
      version: v3
      values: 
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
    syncPolicy:
    automated:
      prune: true
    automated:
      selfHeal: true
