apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-d
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://istio-release.storage.googleapis.com/charts
    chart: istiod
    targetRevision: 1.14.0
    helm:
      version: v3
      values: |
        pilot:
          autoscaleEnabled: true
          autoscaleMin: 3
          autoscaleMax: 5
          replicaCount: 3
        global:
          hub: gcr.io/istio-release
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  syncPolicy:
    automated:
      prune: true
    automated:
      selfHeal: true