apiVersion: v1
kind: Namespace
metadata:
  labels:
    istio-injection: enabled
    kubernetes.io/metadata.name: argocd
  name: argocd
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-ingress-certificiate
  namespace: argocd
spec:
  # Secret names are always required.
  secretName: argocd-ingress-certificiate
  # secretTemplate is optional. If set, these annotations and labels will be
  # copied to the Secret named example-com-tls. These labels and annotations will
  # be re-reconciled if the Certificate's secretTemplate changes. secretTemplate
  # is also enforced, so relevant label and annotation changes on the Secret by a
  # third party will be overwriten by cert-manager to match the secretTemplate.
  duration: 2160h0m0s # 90d
  renewBefore: 360h0m0s # 15d
  subject:
    organizations:
      - jetstack
  # The use of the common name field has been deprecated since 2000 and is
  # discouraged from being used.
  commonName: "*.quest.defimagi.com"
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 4096
  usages:
    - server auth
    - client auth
  # At least one of a DNS Name, URI, or IP address is required.
  dnsNames:
    - "*.quest.defimagi.com"
  # Issuer references are always required.
  issuerRef:
    name: letsencrypt-prod-cluster-issuer
    # We can reference ClusterIssuers by changing the kind here.
    # The default value is Issuer (i.e. a locally namespaced Issuer)
    kind: ClusterIssuer
    # This is optional since cert-manager will default to this value however
    # if you are using an external issuer, change this to that issuer group.
    group: cert-manager.io
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: argocd-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: true
spec:
  tls:
    - hosts:
      - argo.dev.sec.shinra.com
      secretName: argocd-ingress-certificiate
  rules:
  - host: argo.dev.sec.shinra.com
    http:
      paths:
      - path: /
        backend:
          serviceName: argo-cd-argocd-server
          servicePort: 80
