apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod-cluster-issuer
  namespace: cert-manager
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: cogno.infitam@proton.me
    privateKeySecretRef:
      name: issuer-account-key
    solvers:
    - selector:
        dnsZones:
          - "quest.defimagi.com"
      dns01:
        route53:
          region: us-east-1
          hostedZoneID: Z04406002J0F1ZZMSCXJW